import type { RunResult, TestResult } from '@sentinel-ai/playwright-runner';

export interface ReportMeta {
  appId: string;
  suite: string;
  platform: string;
  timestamp: string;
}

function statusIcon(status: TestResult['status']): string {
  switch (status) {
    case 'passed': return 'PASS';
    case 'failed': return 'FAIL';
    case 'timedOut': return 'TIMEOUT';
    case 'skipped': return 'SKIP';
  }
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

/**
 * Convert a RunResult into a Markdown report string.
 */
export function generateMarkdownReport(result: RunResult, meta: ReportMeta): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Test Report: ${meta.appId}`);
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| App | ${meta.appId} |`);
  lines.push(`| Suite | ${meta.suite} |`);
  lines.push(`| Platform | ${meta.platform} |`);
  lines.push(`| Timestamp | ${meta.timestamp} |`);
  lines.push(`| Duration | ${formatDuration(result.duration)} |`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Total | Passed | Failed | Timed Out | Skipped |`);
  lines.push(`|-------|--------|--------|-----------|---------|`);
  lines.push(`| ${result.total} | ${result.passed} | ${result.failed} | ${result.timedOut} | ${result.skipped} |`);
  lines.push('');

  // Overall result
  if (result.failed === 0 && result.timedOut === 0) {
    lines.push('**Result: ALL PASSED**');
  } else {
    lines.push(`**Result: ${result.failed + result.timedOut} FAILURE(S)**`);
  }
  lines.push('');

  // Test details
  lines.push('## Test Details');
  lines.push('');
  lines.push('| # | ID | Title | Status | Duration |');
  lines.push('|---|-----|-------|--------|----------|');

  result.tests.forEach((test, i) => {
    lines.push(
      `| ${i + 1} | ${test.id} | ${test.title} | ${statusIcon(test.status)} | ${formatDuration(test.duration)} |`,
    );
  });

  lines.push('');

  // Failures detail
  const failures = result.tests.filter(
    (t) => t.status === 'failed' || t.status === 'timedOut',
  );

  if (failures.length > 0) {
    lines.push('## Failures');
    lines.push('');

    for (const test of failures) {
      lines.push(`### ${test.id}: ${test.title}`);
      lines.push('');
      lines.push(`- **Status**: ${statusIcon(test.status)}`);
      lines.push(`- **Duration**: ${formatDuration(test.duration)}`);
      if (test.error) {
        lines.push(`- **Error**:`);
        lines.push('```');
        lines.push(test.error);
        lines.push('```');
      }
      if (test.screenshotPath) {
        lines.push(`- **Screenshot**: \`${test.screenshotPath}\``);
      }
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push(`*Generated by sentinel-ai at ${meta.timestamp}*`);
  lines.push('');

  return lines.join('\n');
}
